UPD: run path for install and compile in salixtools. ADD: libs for initrd are now provided in a speicial directory. DEL: rc.keymap is reverted to the default one used in slackware. DEL: some Zenwalkish files (svcblklist, shells). UPD: scripts for building is more verbose and readable now. NEW: grub2 installation even if you boot with syslinux. NEW: mount and /etc/mtab is now complete after booting. UPD: rc.live now uses localesetup and keyboardsetup. NEW: 99 loop devices

diff --git a/install-on-USB b/install-on-USB
--- a/install-on-USB
+++ b/install-on-USB
@@ -2,7 +2,7 @@
 ISO=$1
 MNTDIR=$2
 
-VER=1.0
+VER=1.1
 AUTHOR='Pontvieux Cyrille - jrd@enialis.net'
 LICENCE='GPL v3+'
 version() {
@@ -22,20 +22,37 @@ usage() {
   exit 1
 }
 
+if [ "$UID" -ne "0" ]; then
+  echo "Error : you must run this script as root"
+  exit 2
+fi
+which grub-install > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo "Error : grub2 must be installed on the running system"
+  exit 2
+fi
+MNTDIR=$(echo $MNTDIR|sed 's:/$::')
 if [ ! -f "$ISO" -o ! -d "$MNTDIR" ]; then
   usage
 fi
 DEVPART=$(mount | grep "on $MNTDIR" | cut -d' ' -f1 | head -n 1)
-DEVROOT=${DEVPART%${DEVPART: -1}}
-GAP=$(fdisk -l -u $DEVROOT | grep "^${DEVROOT}1" | awk '{print $3}')
-if [ "$GAP" -lt 63 ]; then
-  echo "Error : the post MBR gap is missing or not enough (63 sectors)."
-  echo "Suggestion : move the first partition (${DEVROOT}1) to reach the gap."
+if [ "$DEVPART" -eq "" ]; then
+  echo "Error : $MNTDIR doesn't seem to be mounted"
   exit 2
+fi
+DEVROOT=${DEVPART%${DEVPART: -1}}
+which fdisk > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+  GAP=$(fdisk -l -u $DEVROOT | grep "^${DEVROOT}1" | awk '{print $3}')
+  if [ "$GAP" -lt 63 ]; then
+    echo "Error : the post MBR gap is missing or not enough (63 sectors)."
+    echo "Suggestion : move the first partition (${DEVROOT}1) to reach the gap."
+    exit 2
+  fi
 fi
 T=$(mktemp -d)
 trap "umount $T; rm -rf $T" INT TERM EXIT
+grub-install --root-directory=$MNTDIR $DEVROOT || exit 5
 mount -o loop $ISO $T || exit 3
 cp -rv $T/* $MNTDIR/ || exit 4
-grub-install --root-directory=$MNTDIR $DEVROOT || exit 5
 exit 0
