salix-live documentation and some fixes: [X] install-on-usb line 40, = instead of -eq [X] include the HOW_TO on the CD and on the Desktop live session [X] include a list of all installed packages [X] Remove root from groups: fuse, plugdev, netdev, power et scanner [X] rc services defaults. [X] update the user "one" settings with the new skeleton from usersettings package [X] Terminal with black solid background [X] Remove core and basic from grub2 boot menu [X] No splashy when booting with grub2=install. [X] Be able to move/resize the first USB partition to make room for the post-MBR-gap => parted resize 1 63s 100%

diff --git a/install-on-USB b/install-on-USB
--- a/install-on-USB
+++ b/install-on-USB
@@ -2,7 +2,7 @@
 ISO=$1
 MNTDIR=$2
 
-VER=1.1
+VER=1.2
 AUTHOR='Pontvieux Cyrille - jrd@enialis.net'
 LICENCE='GPL v3+'
 version() {
@@ -37,7 +37,7 @@ if [ ! -f "$ISO" -o ! -d "$MNTDIR" ]; then
   usage
 fi
 DEVPART=$(mount | grep "on $MNTDIR" | cut -d' ' -f1 | head -n 1)
-if [ "$DEVPART" -eq "" ]; then
+if [ "$DEVPART" = "" ]; then
   echo "Error : $MNTDIR doesn't seem to be mounted"
   exit 2
 fi
@@ -46,14 +46,27 @@ which fdisk > /dev/null 2>&1
 if [ $? -eq 0 ]; then
   GAP=$(fdisk -l -u $DEVROOT | grep "^${DEVROOT}1" | awk '{print $3}')
   if [ "$GAP" -lt 63 ]; then
-    echo "Error : the post MBR gap is missing or not enough (63 sectors)."
-    echo "Suggestion : move the first partition (${DEVROOT}1) to reach the gap."
-    exit 2
+    maxs=$(parted $DEVROOT unit s print |grep '^ 1'|awk '{print $3}')
+    echo "Error : the post MBR gap is missing or not large enough (63 sectors)."
+    echo "Suggestion : slightly move the first partition (${DEVROOT}1) to reach the gap size."
+    echo ""
+    echo "Do you want to slightly reduce this partition to free some space for the required post-MBR-gap?"
+    echo "  parted ${DEVROOT} resize 1 63s $maxs"
+    read -p "y/N ? " R
+    if [ "$R" = "y" -o "$R" = "Y" ]; then
+      umount -f ${DEVROOT}1
+      parted ${DEVROOT} resize 1 63s $maxs
+      ret=$?
+      echo "Please unplug the USB key, re-plug in and re-run this script"
+      exit $ret
+    else
+      exit 2
+    fi
   fi
 fi
 T=$(mktemp -d)
 trap "umount $T; rm -rf $T" INT TERM EXIT
 grub-install --root-directory=$MNTDIR $DEVROOT || exit 5
 mount -o loop $ISO $T || exit 3
-cp -rv $T/* $MNTDIR/ || exit 4
+#cp -rv $T/* $MNTDIR/ || exit 4
 exit 0
